Repository csivitu/code-executor, pull requests merged in 2020-10, with the labels that each got.

#31 feat: v0.1.8
  package.json
Labels: bug, hacktoberfest

#32 WIP: added dockerfiles for the remaining langs
  examples/master.ts
  examples/worker.ts
  src/Builder.ts
  src/CodeExecutor.ts
  src/Runner.ts
  src/Worker.ts
  src/langs/Bash/Dockerfile
  src/langs/Brainfuck/Dockerfile
  src/langs/Brainfuck/start.sh
  src/langs/C/Dockerfile
  src/langs/Golfscript/Dockerfile
  src/langs/Golfscript/start.sh
  src/langs/Java/Dockerfile
  src/langs/Javascript/Dockerfile
  src/langs/O5AB1E/Dockerfile
  src/langs/O5AB1E/start.sh
  src/langs/Perl/Dockerfile
  src/langs/Python/Dockerfile
  src/langs/Ruby/Dockerfile
  src/langs/Rust/Dockerfile
  src/langs/Swift/Dockerfile
  src/utils/findExtension.ts
Labels: enhancement, hacktoberfest

#33 feat: v0.1.9
  examples/master.ts
  examples/worker.ts
  package.json
  src/Builder.ts
  src/CodeExecutor.ts
  src/Runner.ts
  src/Worker.ts
  src/langs/Bash/Dockerfile
  src/langs/Brainfuck/Dockerfile
  src/langs/Brainfuck/start.sh
  src/langs/C/Dockerfile
  src/langs/Golfscript/Dockerfile
  src/langs/Golfscript/start.sh
  src/langs/Java/Dockerfile
  src/langs/Javascript/Dockerfile
  src/langs/O5AB1E/Dockerfile
  src/langs/O5AB1E/start.sh
  src/langs/Perl/Dockerfile
  src/langs/Python/Dockerfile
  src/langs/Ruby/Dockerfile
  src/langs/Rust/Dockerfile
  src/langs/Swift/Dockerfile
  src/utils/findExtension.ts
Labels: enhancement, hacktoberfest

#34 feat: v0.2.0 [BREAKING CHANGE]
  README.md
  examples/master.ts
  examples/worker.ts
  package.json
  src/CodeExecutor.ts
  src/Runner.ts
  src/Worker.ts
  src/index.ts
  src/models/index.ts
  src/utils/saveCode.ts
Labels: enhancement, hacktoberfest

#35 feat: v0.2.0 [BREAKING CHANGE]
  README.md
  examples/master.ts
  examples/worker.ts
  package.json
  src/CodeExecutor.ts
  src/Runner.ts
  src/Worker.ts
  src/index.ts
  src/models/index.ts
  src/utils/saveCode.ts
Labels: enhancement, hacktoberfest

#36 feat: v0.2.1
  package.json
Labels: hacktoberfest

#39 fix: Non root user for Cpp docker
  package-lock.json
  package.json
  src/langs/Cplusplus/Dockerfile
Labels: bug, hacktoberfest

#42 feat: Trim each line before matching output
  src/Runner.ts
  src/utils/matchLines.ts
Labels: bug, enhancement, hacktoberfest

#43 fix: Use trimEnd instead of trim
  package.json
  src/utils/matchLines.ts
Labels: bug, enhancement
